### PR TITLE
Needing full html for other tasks.

### PR DESCRIPTION
**Pull request by hckrmoon**
Usually we need other informations like html title, tag information so pass html full string as well.

### CODE REVIEW

**Comment by samholmes** [comment]
If you need the HTML, why not request it using .getHTML or request itself, then use .parse to parse that HTML? I don't like the idea of making the callback signature more complicated than it has to be.

Also, the goal should be to return the extra information in the meta object itself. Which is planned in the future. PRs for this would be appreciated.

**Comment by hckrmoon** [comment]
Thanks for respond. 

Could you please show me some code about it ? I could not find any method but callback in README file.

**Comment by hckrmoon** [comment]
Ah. I got it now.

However if I need open-graph information and full html at the same time my code would be

```js
const og = require('open-graph');

og('http://example.com', (err, meta) => {
  // do something
});

og.getHTML('http://example.com', (err, meta) => {
  // do something
})
```

which cause that two network connections happen.
That is why I need that full html as a parameter.
Is there anything I am missing ?

**Comment by samholmes** [comment]
You misunderstood the API a bit.

```js
const og = require('open-graph');

og.getHTML('http://example.com', (err, html) => {
  // Do something with the HTML

  var meta = og.parse(html);

  // Do something with the meta
})
```

Basically the default function that open-graph exports does three things: 1) Makes a request for the HTML; 2) passes the HTML into the parse function; 3) returns the meta object that is returned from the parse function.

Keep in mind that you don't have to use getHTML, you could use any HTTP library you want. This library uses the [request](https://github.com/request/request) module internally.

**Comment by hckrmoon** [comment]
Oh you are right. 
Thanks for kind explanation. 😄

**Pull request closed without merging**
